#!/bin/sh

DIRECTORY="isofiles"

if [ ! -d "$DIRECTORY" ]; then
  echo "Folder $DIRECTORY does not exist. Please run extractiso first and try again"
  exit 1
fi

if [ -z "$1" ]; then
  echo "Output file need to be specified."
  exit 1
fi

echo "- Generates MD5 sum"
cd $DIRECTORY/
chmod a+w md5sum.txt
md5sum `find -follow -type f` > md5sum.txt
chmod a-w md5sum.txt

echo "- Edits isolinux.cfg to prevent installation menu (need sudo access)"
chmod a+w isolinux/isolinux.cfg
sudo sed -i '/default vesamenu.c32/d' isolinux/isolinux.cfg
chmod a-w isolinux/isolinux.cfg

echo "- Creates ISO"
cd ..
chmod a+w $DIRECTORY/isolinux/isolinux.bin
genisoimage -r -J -b isolinux/isolinux.bin -c isolinux/boot.cat \
  -no-emul-boot -boot-load-size 4 -boot-info-table \
  -o $1 $DIRECTORY 2> /dev/null

echo "- ISO file successfully created"